package earth.terrarium.chipped.common.defaults;

import earth.terrarium.chipped.Chipped;
import earth.terrarium.chipped.api.BlockType;
import earth.terrarium.chipped.api.PaletteEntry;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.level.block.Blocks;
import net.minecraft.world.level.block.state.BlockBehaviour;

import java.util.Locale;
import java.util.function.Function;

public enum DefaultType implements BlockType {
    ACACIA_LEAVES(Blocks.ACACIA_LEAVES),
    ACACIA_PLANKS(Blocks.ACACIA_PLANKS),
    AMETHYST_BLOCK(Blocks.AMETHYST_BLOCK),
    ANCIENT_DEBRIS(Blocks.ANCIENT_DEBRIS),
    ANDESITE(Blocks.ANDESITE),
    BARREL(Blocks.BARREL),
    BASALT(Blocks.BASALT),
    BIRCH_LEAVES(Blocks.BIRCH_LEAVES),
    BIRCH_PLANKS(Blocks.BIRCH_PLANKS),
    BLACK_CONCRETE(Blocks.BLACK_CONCRETE),
    BLACK_GLAZED_TERRACOTTA(Blocks.BLACK_GLAZED_TERRACOTTA),
    BLACK_STAINED_GLASS(Blocks.BLACK_STAINED_GLASS),
    BLACK_TERRACOTTA(Blocks.BLACK_TERRACOTTA),
    BLACK_WOOL(Blocks.BLACK_WOOL),
    BLACKSTONE(Blocks.BLACKSTONE),
    BLUE_CONCRETE(Blocks.BLUE_CONCRETE),
    BLUE_GLAZED_TERRACOTTA(Blocks.BLUE_GLAZED_TERRACOTTA),
    BLUE_ICE(Blocks.BLUE_ICE),
    BLUE_STAINED_GLASS(Blocks.BLUE_STAINED_GLASS),
    BLUE_TERRACOTTA(Blocks.BLUE_TERRACOTTA),
    BLUE_WOOL(Blocks.BLUE_WOOL),
    BOOKSHELF(Blocks.BOOKSHELF),
    BRICKS(Blocks.BRICKS),
    BROWN_CONCRETE(Blocks.BROWN_CONCRETE),
    BROWN_GLAZED_TERRACOTTA(Blocks.BROWN_GLAZED_TERRACOTTA),
    BROWN_MUSHROOM(Blocks.BROWN_MUSHROOM),
    BROWN_MUSHROOM_BLOCK(Blocks.BROWN_MUSHROOM_BLOCK),
    BROWN_STAINED_GLASS(Blocks.BROWN_STAINED_GLASS),
    BROWN_TERRACOTTA(Blocks.BROWN_TERRACOTTA),
    BROWN_WOOL(Blocks.BROWN_WOOL),
    CALCITE(Blocks.CALCITE),
    CLAY(Blocks.CLAY),
    COAL_BLOCK(Blocks.COAL_BLOCK),
    COBBLESTONE(Blocks.COBBLESTONE),
    COBWEB(Blocks.COBWEB),
    COPPER_BLOCK(Blocks.COPPER_BLOCK),
    CRIMSON_FUNGUS(Blocks.CRIMSON_FUNGUS),
    CRIMSON_PLANKS(Blocks.CRIMSON_PLANKS),
    CRIMSON_ROOTS(Blocks.CRIMSON_ROOTS),
    CRYING_OBSIDIAN(Blocks.CRYING_OBSIDIAN),
    CYAN_CONCRETE(Blocks.CYAN_CONCRETE),
    CYAN_GLAZED_TERRACOTTA(Blocks.CYAN_GLAZED_TERRACOTTA),
    CYAN_STAINED_GLASS(Blocks.CYAN_STAINED_GLASS),
    CYAN_TERRACOTTA(Blocks.CYAN_TERRACOTTA),
    CYAN_WOOL(Blocks.CYAN_WOOL),
    DARK_OAK_LEAVES(Blocks.DARK_OAK_LEAVES),
    DARK_PRISMARINE(Blocks.DARK_PRISMARINE),
    DEEPSLATE(Blocks.DEEPSLATE),
    DIAMOND_BLOCK(Blocks.DIAMOND_BLOCK),
    DIORITE(Blocks.DIORITE),
    DIRT(Blocks.DIRT),
    DRIED_KELP_BLOCK(Blocks.DRIED_KELP_BLOCK),
    DRIPSTONE_BLOCK(Blocks.DRIPSTONE_BLOCK),
    EMERALD_BLOCK(Blocks.EMERALD_BLOCK),
    END_STONE(Blocks.END_STONE),
    GILDED_BLACKSTONE(Blocks.GILDED_BLACKSTONE),
    GLASS(Blocks.GLASS),
    GLASS_PANE(Blocks.GLASS_PANE),
    GLOWSTONE(Blocks.GLOWSTONE),
    GOLD_BLOCK(Blocks.GOLD_BLOCK),
    GRANITE(Blocks.GRANITE),
    GRAY_CONCRETE(Blocks.GRAY_CONCRETE),
    GRAY_GLAZED_TERRACOTTA(Blocks.GRAY_GLAZED_TERRACOTTA),
    GRAY_STAINED_GLASS(Blocks.GRAY_STAINED_GLASS),
    GRAY_TERRACOTTA(Blocks.GRAY_TERRACOTTA),
    GRAY_WOOL(Blocks.GRAY_WOOL),
    GREEN_CONCRETE(Blocks.GREEN_CONCRETE),
    GREEN_GLAZED_TERRACOTTA(Blocks.GREEN_GLAZED_TERRACOTTA),
    GREEN_STAINED_GLASS(Blocks.GREEN_STAINED_GLASS),
    GREEN_TERRACOTTA(Blocks.GREEN_TERRACOTTA),
    GREEN_WOOL(Blocks.GREEN_WOOL),
    HAY_BLOCK(Blocks.HAY_BLOCK),
    ICE(Blocks.ICE),
    IRON_BLOCK(Blocks.IRON_BLOCK),
    JUNGLE_LEAVES(Blocks.JUNGLE_LEAVES),
    JUNGLE_PLANKS(Blocks.JUNGLE_PLANKS),
    LANTERN(Blocks.LANTERN),
    LAPIS_BLOCK(Blocks.LAPIS_BLOCK),
    LIGHT_BLUE_CONCRETE(Blocks.LIGHT_BLUE_CONCRETE),
    LIGHT_BLUE_GLAZED_TERRACOTTA(Blocks.LIGHT_BLUE_GLAZED_TERRACOTTA),
    LIGHT_BLUE_STAINED_GLASS(Blocks.LIGHT_BLUE_STAINED_GLASS),
    LIGHT_BLUE_TERRACOTTA(Blocks.LIGHT_BLUE_TERRACOTTA),
    LIGHT_BLUE_WOOL(Blocks.LIGHT_BLUE_WOOL),
    LIGHT_GRAY_CONCRETE(Blocks.LIGHT_GRAY_CONCRETE),
    LIGHT_GRAY_GLAZED_TERRACOTTA(Blocks.LIGHT_GRAY_GLAZED_TERRACOTTA),
    LIGHT_GRAY_STAINED_GLASS(Blocks.LIGHT_GRAY_STAINED_GLASS),
    LIGHT_GRAY_TERRACOTTA(Blocks.LIGHT_GRAY_TERRACOTTA),
    LIGHT_GRAY_WOOL(Blocks.LIGHT_GRAY_WOOL),
    LILY_PAD(Blocks.LILY_PAD),
    LIME_CONCRETE(Blocks.LIME_CONCRETE),
    LIME_GLAZED_TERRACOTTA(Blocks.LIME_GLAZED_TERRACOTTA),
    LIME_STAINED_GLASS(Blocks.LIME_STAINED_GLASS),
    LIME_TERRACOTTA(Blocks.LIME_TERRACOTTA),
    LIME_WOOL(Blocks.LIME_WOOL),
    LODESTONE(Blocks.LODESTONE),
    MAGENTA_CONCRETE(Blocks.MAGENTA_CONCRETE),
    MAGENTA_GLAZED_TERRACOTTA(Blocks.MAGENTA_GLAZED_TERRACOTTA),
    MAGENTA_STAINED_GLASS(Blocks.MAGENTA_STAINED_GLASS),
    MAGENTA_TERRACOTTA(Blocks.MAGENTA_TERRACOTTA),
    MAGENTA_WOOL(Blocks.MAGENTA_WOOL),
    MAGMA_BLOCK(Blocks.MAGMA_BLOCK),
    MELON(Blocks.MELON),
    MOSSY_COBBLESTONE(Blocks.MOSSY_COBBLESTONE),
    MOSSY_STONE_BRICKS(Blocks.MOSSY_STONE_BRICKS),
    NETHER_BRICKS(Blocks.NETHER_BRICKS),
    NETHER_SPROUTS(Blocks.NETHER_SPROUTS),
    NETHER_WART_BLOCK(Blocks.NETHER_WART_BLOCK),
    NETHERITE_BLOCK(Blocks.NETHERITE_BLOCK),
    NETHERRACK(Blocks.NETHERRACK),
    OAK_LEAVES(Blocks.OAK_LEAVES),
    OAK_PLANKS(Blocks.OAK_PLANKS),
    OBSIDIAN(Blocks.OBSIDIAN),
    ORANGE_CONCRETE(Blocks.ORANGE_CONCRETE),
    ORANGE_GLAZED_TERRACOTTA(Blocks.ORANGE_GLAZED_TERRACOTTA),
    ORANGE_STAINED_GLASS(Blocks.ORANGE_STAINED_GLASS),
    ORANGE_TERRACOTTA(Blocks.ORANGE_TERRACOTTA),
    ORANGE_WOOL(Blocks.ORANGE_WOOL),
    PACKED_ICE(Blocks.PACKED_ICE),
    PINK_CONCRETE(Blocks.PINK_CONCRETE),
    PINK_GLAZED_TERRACOTTA(Blocks.PINK_GLAZED_TERRACOTTA),
    PINK_STAINED_GLASS(Blocks.PINK_STAINED_GLASS),
    PINK_TERRACOTTA(Blocks.PINK_TERRACOTTA),
    PINK_WOOL(Blocks.PINK_WOOL),
    PURPUR_BLOCK(Blocks.PURPUR_BLOCK),
    QUARTZ_BLOCK(Blocks.QUARTZ_BLOCK),
    RAW_COPPER_BLOCK(Blocks.RAW_COPPER_BLOCK),
    RAW_GOLD_BLOCK(Blocks.RAW_GOLD_BLOCK),
    RAW_IRON_BLOCK(Blocks.RAW_IRON_BLOCK),
    RED_CONCRETE(Blocks.RED_CONCRETE),
    RED_GLAZED_TERRACOTTA(Blocks.RED_GLAZED_TERRACOTTA),
    RED_MUSHROOM(Blocks.RED_MUSHROOM),
    RED_MUSHROOM_BLOCK(Blocks.RED_MUSHROOM_BLOCK),
    RED_NETHER_BRICK(Blocks.RED_NETHER_BRICKS),
    RED_SANDSTONE(Blocks.RED_SANDSTONE),
    RED_STAINED_GLASS(Blocks.RED_STAINED_GLASS),
    RED_TERRACOTTA(Blocks.RED_TERRACOTTA),
    RED_WOOL(Blocks.RED_WOOL),
    REDSTONE_BLOCK(Blocks.REDSTONE_BLOCK),
    REDSTONE_LAMP(Blocks.REDSTONE_LAMP),
    REDSTONE_TORCH(Blocks.REDSTONE_TORCH),
    SAND(Blocks.SAND),
    SANDSTONE(Blocks.SANDSTONE),
    SEA_LANTERN(Blocks.SEA_LANTERN),
    SHROOMLIGHT(Blocks.SHROOMLIGHT),
    SMOOTH_STONE(Blocks.SMOOTH_STONE),
    SNOW_BLOCK(Blocks.SNOW_BLOCK),
    SOUL_SAND(Blocks.SOUL_SAND),
    SPRUCE_LEAVES(Blocks.SPRUCE_LEAVES),
    SPRUCE_PLANKS(Blocks.SPRUCE_PLANKS),
    STONE(Blocks.STONE),
    TERRACOTTA(Blocks.TERRACOTTA),
    TORCH(Blocks.TORCH),
    TUFF(Blocks.TUFF),
    VINE(Blocks.VINE),
    WARPED_FUNGUS(Blocks.WARPED_FUNGUS),
    WARPED_PLANKS(Blocks.WARPED_PLANKS),
    WARPED_ROOTS(Blocks.WARPED_ROOTS),
    WARPED_WART_BLOCK(Blocks.WARPED_WART_BLOCK),
    WHITE_CONCRETE(Blocks.WHITE_CONCRETE),
    WHITE_GLAZED_TERRACOTTA(Blocks.WHITE_GLAZED_TERRACOTTA),
    WHITE_STAINED_GLASS(Blocks.WHITE_STAINED_GLASS),
    WHITE_TERRACOTTA(Blocks.WHITE_TERRACOTTA),
    WHITE_WOOL(Blocks.WHITE_WOOL),
    YELLOW_CONCRETE(Blocks.YELLOW_CONCRETE),
    YELLOW_GLAZED_TERRACOTTA(Blocks.YELLOW_GLAZED_TERRACOTTA),
    YELLOW_STAINED_GLASS(Blocks.YELLOW_STAINED_GLASS),
    YELLOW_TERRACOTTA(Blocks.YELLOW_TERRACOTTA),
    YELLOW_WOOL(Blocks.YELLOW_WOOL),
    ;

    private final String id;
    private final BlockBehaviour.Properties properties;

    DefaultType(String id, BlockBehaviour.Properties properties) {
        this.id = id;
        this.properties = properties;
    }

    DefaultType(Block block) {
        this.id = this.name().toLowerCase(Locale.ROOT);
        this.properties = props(block);
    }

    @Override
    public String translationKey() {
        return String.join(".", "block_type", Chipped.MOD_ID, id);
    }

    @Override
    public Function<PaletteEntry, BlockBehaviour.Properties> properties() {
        return entry -> properties;
    }

    @Override
    public String id() {
        return id;
    }

    public static BlockBehaviour.Properties props(Block block) {
        return BlockBehaviour.Properties.copy(block);
    }
}
